### ISSUE TITLE
Broken example in README.MD

### ISSUE THREAD

**Issue by mist475** [piegamesde/nbt#4]
the code snippet:
```java
try (RegionFile regionFile = new RegionFile(Paths.get(myWorld, "region", "r.0.0.mca"))) {
	for (Chunk chunk : regionFile.listChunks()) {
		CompoundTag data = chunk.readTag();
	}
}
```

in README.md is listed as a way to read chunk data, however, the listChunks() method returns a List<Integer> which can't be cast to a Chunk,
I suggest replacing it with this or something better:
```java
try (RegionFile regionFile = new RegionFile(Paths.get(myWorld, "region", "r.0.0.mca"))) {
	List<Integer> list = regionFile.listChunks();
	for (int i : list) {
		Chunk chunk = regionFile.loadChunk(i);
		CompoundTag data = chunk.readTag();
	}
}
```

**Comment by piegamesde** [comment]
Huh, how did I miss the notification? Anyways, thanks for reporting.

**Comment by piegamesde** [comment]
To be honest this code is rather ugly, but a) you can't for loop over a `Stream` in Java and b) you can't have exceptions in a `Stream` so none of the better solutions that I could think are expressible in Java.
